#+TITLE: Hannover Night Emacs Theme
#+AUTHOR: Florian Rommel
#+LANGUAGE: en

[[./images/c.svg]]

[[./images/c-lsp-corfu.svg]]

[[./images/lisp.svg]]

[[./images/org.svg]]

A dark Emacs theme with moderate contrast.
Provides carefully crafted faces for lots of packages.

Colors and some other aspects of the theme can be configured
(See the hannover-night group).

The main colors are exported as global variables, so they can be used for
customizations.


* Installation

Clone the repository:
#+BEGIN_SRC shell
git clone git://github.com/florommel/hannover-night-theme.git
#+END_SRC

Include the theme in your init file:
#+BEGIN_SRC emacs-lisp
(add-to-list 'custom-theme-load-path "/path/to/the/cloned/theme/")
(load-theme 'hannover-night t)
#+END_SRC


* Tips

You can customize the colors and other parameters.
Have a look at the ~hannover-night-theme~ group.

If you use ~powerline~ or similar packages, you might want to set
~hannover-night-mode-box-width~ to 0 or 1.


* Supported Packages

tab-line, tab-bar, powerline, window-divider, term, multiple cursors,
dired, diredfl, magit, diff, diff-hl, git-gutter, wgrep, avy, anzu,
ivy/swiper, selectrum, vertico, orderless, paren showing, compilation,
display-line-numbers, company, company-posframe, popup, corfu,
rainbow-delimiters, highlight, highlight-changes, symbol-overlay,
bookmark, bm, sh, auctex, outline, org, hyperbole, devdocs, markdown,
flymake, Flyspell, Flycheck, hexl, imenu-list, ledger, neotree,
goggles, tree-sitter, eglot, lsp, treemacs, yascroll, which-func
